name: EAS TestFlight — iOS

on:
  push:
    branches:
      - main

defaults:
  tools:
    node: '20'

jobs:
  build_ios:
    name: Build iOS Production
    type: build
    params:
      platform: ios
      profile: production

  testflight_ios:
    name: Upload Build to TestFlight
    type: testflight
    needs:
      - build_ios
    params:
      build_id: ${{ needs.build_ios.outputs.build_id }}
      profile: production
